- id: '1565483224890'
  alias: Light on sunset
  trigger:
  - event: sunset
    offset: -00:20:00
    platform: sun
  condition:
  - condition: state
    entity_id: device_tracker.gm1917
    state: home
  action:
  - data:
      entity_id: light.room_light
    service: light.turn_on
- id: '1565483460783'
  alias: Room speaker 40% AC On
  trigger:
  - entity_id: switch.bedroom_a_c
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - after: 06:00
    before: '22:00'
    condition: time
  action:
  - data:
      entity_id: media_player.room_speaker
      volume_level: 0.4
    service: media_player.volume_set
- id: '1565483561556'
  alias: Room speaker 60% AC on
  trigger:
  - entity_id: switch.living_room_ac
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - after: 06:00
    before: '22:00'
    condition: time
  action:
  - data:
      entity_id: media_player.room_speaker
      volume_level: 0.6
    service: media_player.volume_set
- id: '1565485013479'
  alias: Lights off when away
  trigger:
  - entity_id: device_tracker.gm1917
    from: home
    platform: state
    to: not_home
  condition: []
  action:
  - data:
      entity_id: light.room_light
    service: light.turn_off
- id: '1565547129250'
  alias: watch dnd
  trigger:
  - platform: mqtt
    topic: watch
  condition: []
  action:
  - data_template:
      message: '{{ trigger.payload }}'
    service: persistent_notification.create
- id: '1566963612395'
  alias: Rpi4 overheat warning
  trigger:
  - platform: mqtt
    topic: rpi4Temp/
  condition:
  - condition: template
    value_template: '{{float(trigger.payload) > 75.0}}'
  action:
  - data:
      message: Temperature reached 75. Do something!
      target:
      - '617024318626594831'
    service: notify.discord
- id: '1567128567269'
  alias: Lights on when home and sunset
  trigger:
  - entity_id: device_tracker.gm1917
    from: not_home
    platform: state
    to: home
  condition:
  - after: sunset
    condition: sun
  action:
  - data:
      entity_id: light.room_light
    service: light.turn_on
  - data:
      message: '{{  now().hour }}:{{ now().minute}}:{{now().second}} Lights on'
      target:
      - '617157127303069697'
    service: notify.discord
- id: '1569030746865'
  alias: Turn on display
  trigger:
  - entity_id: device_tracker.gm1917
    from: not_home
    platform: state
    to: home
  - at: 06:00
    platform: time
  condition: []
  action:
  - service: shell_command.turn_on_display
- id: '1569370954697'
  alias: Turn off display
  trigger:
  - entity_id: device_tracker.gm1917
    from: home
    platform: state
    to: not_home
  - at: '22:30'
    platform: time
  condition: []
  action:
  - service: shell_command.turn_off_display
- id: '1569730184552'
  alias: Auto renew SSL
  trigger:
    platform: numeric_state
    entity_id: sensor.ssl_cert_expiry
    below: 29
  action:
    service: shell_command.renew_ssl
- id: '1569730184553'
  alias: Auto renew SSL
  trigger:
    platform: numeric_state
    entity_id: sensor.ssl_cert_expiry
    below: 29
  action:
    service: shell_command.renew_ssl
- id: '1576083084283'
  alias: Kindle Charger State Change
  trigger:
  - entity_id: switch.kindle_charger
    from: 'on'
    platform: state
    to: 'off'
  - entity_id: switch.kindle_charger
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data_template:
      channel: !secret slack_channel_id
      message: is {{ trigger.to_state.state }}
    service: script.notify_slack
- id: '1583886054389'
  alias: Light auto color temperature
  description: ''
  trigger:
  - entity_id: light.room_light
    from: 'off'
    platform: state
    to: 'on'
  - at: '18:00'
    platform: time
  - at: '18:30'
    platform: time
  - at: '19:00'
    platform: time
  - at: '19:30'
    platform: time
  - at: '20:00'
    platform: time
  - at: '20:30'
    platform: time
  - at: '21:00'
    platform: time
  condition: []
  action:
    service_template: >
      {% if is_state('light.room_light','off') %}
        light.turn_off
      {% else %}
        light.turn_on
      {%- endif %}
    data_template:
      entity_id: light.room_light
      transition: 4
      #set color from white to yellow (in temperature) from 6PM to 9PM
      kelvin: >
        {% if ((now().hour >= 9) and (now().hour < 18)) %}
          6000
        {% elif ((now().hour == 18) and (now().minute < 30)) %}
          6000
        {% elif ((now().hour == 18) and (now().minute >= 30)) %}
          5500
        {% elif ((now().hour == 19) and (now().minute < 30)) %}
          5000
        {% elif ((now().hour == 19) and (now().minute >= 30)) %}
          4500
        {% elif ((now().hour == 20) and (now().minute < 30)) %}
          4000
        {% elif ((now().hour == 20) and (now().minute >= 30)) %}
          3500
        {% else %}
          2700
        {%- endif %}

